spring:
  application:
    name: analytics-service
  profiles:
    active: analytics
  config:
    import: 'configserver:http://localhost:8888'
  cloud:
    config:
      uri: http://localhost:8888
      name: analytics-service,config-client
      username: spring_cloud_user
      password: '1234'

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 2

log:
  app-name: analytics-service