server:
  port: 8888

logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/baverma/Documents/Microservices/microservices-demo/config-server-repository
  security:
    user:
      name: spring_cloud_user
      password: '1234'

log:
  app-name: config-server